version: '3.8'

services:
  auth-service:
    build: ./microservices/auth-service
    ports:
      - "5001:5001"

  user-service:
    build: ./microservices/user-service
    ports:
      - "5002:5002"

  job-service:
    build: ./microservices/job-service
    ports:
      - "5003:5003"

